spring:
  application:
    name: order-service
  rabbitmq:
    host: 192.168.91.131
    port: 5672
    username: admin
    password: admin   
#server:
 # port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#无需额外配置，feign 默认已启用了 ribbon 负载均衡和重试机制
#可以通过配置对参数进行调整

#feign 启用 hystrix      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202
  